import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Provider } from "react-redux";
import store from "@/store";

const work_Sans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 
    <html lang="en">
      <body className={work_Sans.className}>
        <div className="container">
        <Navbar/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
   
  );
}
