import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ReduxProvider } from "@/store";
import store from "@/store";
import styles from './layout.module.css'


const work_Sans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={work_Sans.className}>
        <ReduxProvider store={store}>
        <div className={styles.container}>
          <div className={styles.navbar}>
          <Navbar />
          </div>
          <div className={styles.children}>
          {children}
          </div>
          <Footer />
        </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
