import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Image from "next/image";

const work_Sans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={work_Sans.className}>
        <div className="container">
        <Navbar/>
        <Image src='/clouds.png' style={{position:'absolute', right:'110px', top:'60px'}} width={300} height={100}/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  );
}
